name: Docker Build & Deploy

on:
  workflow_run:
    workflows: ["CI Maven"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 📦 Descargar artefacto del CI
      - name: Descargar JAR
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: "CI Maven"
          run_id: ${{ github.event.workflow_run.id }}
          name: store-app-jar
          path: artifact/

      # 🐳 Build imagen (ahora SÍ usa artifact)
      - name: Build Docker image
        run: docker build -t store-app .

      # 🧹 limpiar
      - name: Down previo
        run: docker compose down -v || true

      # 🚀 levantar
      - name: Up entorno
        run: docker compose up -d

      # ⏳ healthcheck
      - name: Esperar app
        run: |
          for i in {1..24}; do
            if curl -fsS http://localhost:8888/actuator/health; then
              exit 0
            fi
            sleep 5
          done
          docker compose logs
          exit 1

      # logs
      - name: Logs si falla
        if: failure()
        run: |
          mkdir logs
          docker compose logs > logs/all.log

      - name: Subir logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Clean
        if: always()
        run: docker compose down -v
